### ISSUE TITLE
DJV 2.0.8 - File next/previous zooms out

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#324] opened 2020-07-03 14:36 UTC
DO:
- open 2 clips
- "File next/previous" (PgUp/PgDown or use toolbar "file" dropdown)

HAPPEN
- zooms out on one of the clips while maintaining size on the other

SHOULD:
- not change zoom

NOTES:
- this is somehow a one-timer, so far I could not reproduce after closing both files 
- logfile [djv.log.zip](https://github.com/darbyjohnston/DJV/files/4870202/djv.log.zip)

**Comment by aberkl** [comment] 2020-07-03 17:34
> * this is somehow a one-timer, so far I could not reproduce after closing both files

Happened again, but still not sure how to reproduce

**Comment by darbyjohnston** [comment] 2020-07-03 18:47
I haven't seen this before and cannot reproduce it either; how much is it zooming and is the zoom animated like when using the "+" and "-" keys?

**Comment by aberkl** [comment] 2020-07-03 19:52
Typically after opening a clip I set "View > Frame" (shortcut "."). Just had it after setting one clip to "View > Fill" (shortcut "BACKSPACE") - but once again only a one-timer.

Is there an extended logging I can activate that maybe records every keystroke/action?

**Comment by aberkl** [comment] 2020-07-03 19:55
Maybe also worth to mention: Found this on the Linux version.

**Comment by aberkl** [comment] 2020-07-03 21:43
And again, see screen recording, this time zoomed in: [issue.mp4.zip](https://github.com/darbyjohnston/DJV/files/4871549/issue.mp4.zip)

**Comment by aberkl** [comment] 2020-07-03 22:39
Once you are in this state (yes, it happened again) simply clicking the different windows changes their zoom value as well. In other words: Giving focus changes zoom value.

BTW: No longer one-timer but occasionally.

**Comment by darbyjohnston** [comment] 2020-07-03 23:22
Thanks for the video, it looks like the problem occurs when the scroll wheel is used for zooming. I hadn't noticed it before since I mostly use a tablet instead of a mouse. I checked in a fix to my local code branch and will include it with the next release.

**Closed** 2020-07-03 23:23 UTC
Labels: bug
