### ISSUE TITLE
DJV 2.0 Feature request: Add option to save output of "Information"

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#317] opened 2020-06-21 14:28 UTC
There should be an option to save the output of "Information" (including Search in "Information") to a textfile. Default name should be {filename}.txt, i.e. **C001C003_140702_R3VJ.txt** for clip **C001C003_140702_R3VJ.mov**.

**Comment by darbyjohnston** [comment] 2020-07-17 17:58
Closing this as a duplicate of:
https://github.com/darbyjohnston/DJV/issues/37

**Closed** 2020-07-17 17:58 UTC
Labels: duplicate, enhancement
