### ISSUE TITLE
Erratic backwards playback

### ISSUE THREAD

**Issue by PiOverFour** [darbyjohnston/DJV#243] opened 2020-03-18 11:47 UTC
When playing backwards, the frames seem to be unloaded every time the sequence loops: the timeline switches between green and orange at every cycle. This leads to constant disk access and memory fluctuating. The CPU usage is also much higher (on my computer, ~50% vs. ~5% when playing forwards). It doesn’t happen when playing forwards.

**Comment by darbyjohnston** [comment] 2020-04-26 18:26
Hi, I just checked in a fix for the cache behavior with backwards playback; this also fixes the CPU usage spike which was being caused by the uncached frames being reloaded.

**Closed by darbyjohnston** 2020-04-26 18:26 UTC
Labels: bug

**Comment by PiOverFour** [comment] 2020-04-26 21:42
It works perfectly, thanks!

**Comment by darbyjohnston** [comment] 2020-04-28 17:45
Thanks again for testing it out! Hopefully the new changes to the build system were not too confusing...

**Comment by PiOverFour** [comment] 2020-04-28 18:07
They were, until I read the manual :D Then I rebuilt from scratch and it was all right. The only problem I had was with dependencies for third-party packages, many of which are not listed, but which give warnings at each step so I knew what to install.
I reinstalled my system and compiled various things, so this list may not be entirely relevant for DJV, but if it’s of any use, looking at the history I did something like:
``` sh
sudo apt install libsdl2-dev libglfw3-dev nasm libasound2-dev libxi-dev libxcursor-dev libxinerama-dev libxrandr-dev libgl-dev glx libopengl-dev g++ gcc cmake git
```

**Comment by darbyjohnston** [comment] 2020-04-28 18:23
Thanks for the list, is this on Ubuntu? One of my pet peeves about Linux is how granular the packages are, it would be nice to to have super-sets so you could install "x11-dev" instead of half a dozen different ones. :)

The build steps are a bit more complicated now but it fixed some subtle CMake dependency issues that were a real pain to track down. It also makes compiling/iterating on the DJV code a lot faster since CMake doesn't have to check every dependency each time.

**Comment by PiOverFour** [comment] 2020-04-29 10:11
> Thanks for the list, is this on Ubuntu?

No, this is Debian now, but I checked that Ubuntu uses the same package names. I made a mistake in copying the list: `glx` is not a package, either on Debian nor in Ubuntu.

> One of my pet peeves about Linux is how granular the packages are, it would be nice to to have super-sets so you could install "x11-dev" instead of half a dozen different ones. :)

Ha ha I wish I’d thought of looking that up before! [Here](https://packages.debian.org/buster/xorg-dev) is one for Debian, [here](https://packages.ubuntu.com/focal/xorg-dev) is the same for Ubuntu, as well as [this one](https://packages.debian.org/buster/build-essential). These two reduce the command to:

``` sh
apt install git cmake build-essential xorg-dev libsdl2-dev libglfw3-dev nasm libasound2-dev libgl-dev libopengl-dev
```
Maybe some of these exist in further metapackages, but I couldn’t find them.

**Comment by darbyjohnston** [comment] 2020-04-30 00:43
Ah, that is more convenient. :) I fired up a VM and after some experimentation was able to reduce the command to:
```
sudo apt-get install git cmake build-essential libgl1-mesa-dev xorg-dev libasound2-dev
```
I also added it to the documentation.
