### ISSUE TITLE
DJV 2.0.3: playback "shaky"

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#145] opened 2019-09-16 13:26 UTC
DO:
- open [clip](https://github.com/darbyjohnston/DJV/files/3616440/shaky.mp4.zip)  in both DJV 1.3.0 and 2.0.3

HAPPEN:
- DJV 1.3.0 plays fine
- DJV 2.0.3 shows a "shaky" image, best seen in the overlays around the actual image

SHOULD:
- play fine

**Comment by darbyjohnston** [comment] 2019-09-16 17:45
It looks like the "shakiness" is being caused by the scaling filter changing randomly on different frames; I haven't seen this before, I'll check it out. Here are two screen shots showing the difference between frames.
![DJV Shaky 1](https://user-images.githubusercontent.com/8532558/64980608-05b18400-d86f-11e9-812a-2dfaab4f6ee4.PNG)
![DJV Shaky 2](https://user-images.githubusercontent.com/8532558/64980622-0ba76500-d86f-11e9-9605-ab1e858839cf.PNG)

**Comment by darbyjohnston** [comment] 2019-09-16 18:06
OK, I fixed the issue, the scaling filter was getting randomly changed each frame. Not sure why I had not seen that before, but thanks for reporting it, good eyes!

PS. As far as I can tell GitHub issues are only opened/closed (ie, no "pending" like SourceForge), so I'm going to close this issue as fixed, but it can be re-opened if you spot any problems after the new version is out.

**Closed by darbyjohnston** 2019-09-16 18:06 UTC
Labels: bug

**Comment by aberkl** [comment] 2019-09-16 19:29
Funny, just tried it on my "home" machine and could not really reproduce the problem - although I used 1:1 pixel mapping in both cases.

But good to know you found something!
