### ISSUE TITLE
Mouse position is wonky

### ISSUE THREAD

**Issue by jminor** [darbyjohnston/DJV#190] opened 2020-01-07 07:08 UTC
I am having trouble clicking on anything in DJV on my Mac laptop, including the menus. It appears that the mouse coordinates are off by a factor of 2. For example, if my mouse is in the middle of the screen, then I can interact with things that are 1/4 from the top-left. I suspect this is a Mac Retina display issue. I will try to A/B compare on a retina versus non-retina display to be sure.

**Comment by darbyjohnston** [comment] 2020-01-07 19:01
Hi Josh, thanks for the bug report, this definitely sounds like an issue with the Retina display. Are you compiling from source or using one of the packaged releases? If you are compiling from source and don't mind testing some changes I can try making a quick change that might fix the issue.

Also would you mind checking the DJV log on the Retina machine to see what the "content scale" is reported as?
> egrep -i "content scale" ~/Documents/DJV/djv.log

**Comment by jminor** [comment] 2020-01-07 19:34
I confirmed that this problem only occurs when DJV is on a retina screen (the built-in display of my MacBook Pro). If I move the window to a 2nd monitor which is not retina, it works fine.

I'm using the released build of 2.0.5. I see the same issue with 2.0.4 and 2.0.3.

If I launch DJV with only the retina display active, then I see "Window content scale: 2x2" in the log. If I launch it with only the non-retina display, then I see "Window content scale: 1x1" in the log.

Regardless of which one I see in the log, or what the monitor setup is active at launch, I can then plug in the other display and move the app to the other monitor and the results are self-consistent. When on the retina display the mouse coords are incorrect, and on the non-retina display they are correct. Since this can change at runtime, perhaps the content scale needs to be queried dynamically.

**Comment by darbyjohnston** [comment] 2020-01-07 20:05
The content scale should be dynamic, which sounds like it is working if you can move the DJV window between monitors and it looks the same on both. However the DPI value is currently only logged at start-up, I should probably change that so it is logged any time the value changes.

I think the issue is that the content scale needs to be applied to the mouse coordinates coming from GLFW, and probably and other coordinates like drag and drop. I'll add that for the next release.

**Comment by jminor** [comment] 2020-01-07 20:11
I was able to build it locally, so I'm happy to verify a fix if that's helpful.

---
Joshua Minor (he-him)
Pixar Studio Tools Story/Editorial/VR Previs Tech Lead
joshm@pixar.com

**Comment by darbyjohnston** [comment] 2020-01-08 02:33
Cool, thanks; I just checked in changes to scale the mouse cursor by the content scale, and write to the log whenever the DPI is changed. When you get a chance try pulling the latest and see if that fixes the issue.

**Comment by darbyjohnston** [comment] 2020-01-08 02:40
Related issue: https://github.com/darbyjohnston/DJV/issues/94

**Comment by darbyjohnston** [comment] 2020-04-14 17:32
I found someone who was able to test this and it looks like it is fixed with the latest code in the master branch, yay! :)

**Closed by darbyjohnston** 2020-04-14 17:32 UTC
Labels: bug
