### ISSUE TITLE
DJV 2.0.8 - Color Picker shows (1 1 1) for black, (254 254 254) for white

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#325] opened 2020-07-03 15:58 UTC
DO:
- open any image/clip containing pure white and black

HAPPEN
- Color Picker shows (1 1 1) for black, (254 254 254) for white

SHOULD:
- show (0 0 0) for black, (255 255 255) for white

NOTES:
- other in-between values (of the attached ramp) are fine
- works as expected in DJV 1.3.0 

![Ramp](https://user-images.githubusercontent.com/9915206/86484501-a4539680-bd56-11ea-98f8-c95d694ef813.png)

**Comment by darbyjohnston** [comment] 2020-07-03 18:51
It seems this is an issue with the OpenColorIO color management, if you click on the color picker gear icon and uncheck "Apply color space" you should get the correct values. I believe the next version of OpenColorIO is planning on having better color accuracy. I'm going to close this issue since it's a duplicate of:
https://github.com/darbyjohnston/DJV/issues/304

**Closed by darbyjohnston** 2020-07-03 18:51 UTC
